import React from 'react'

function Footer() {
  return (
    <div className='text-center text-[#ffffff] mt-20'>
      <h2 >Created By Fravel || AI-TRIP_PLANNER </h2>
      <h2>© {new Date().getFullYear()} All rights are reserved by Fravel - the AI trip planner</h2>
      <p className='text-[#969696] text-xs '>Note : Results and Images  generated by AI may include inaccuracies . Cross-check before making decisions.</p>
    </div>
  )
}

export default Footer
